package vn.campuslife.enumeration;

public enum ScoreEntrySourceType {
    ACTIVITY_PARTICIPATION,
    ACTIVITY_REGISTRATION,
    TASK_SUBMISSION,
    TASK_ASSIGNMENT,
    MINIGAME_ATTEMPT,
    SERIES_PROGRESS,
    SERIES_MINIMUM_REQUIREMENT,
    MANUAL_ADJUSTMENT,
    RECALCULATION
}
