name: ci

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Test
        run: ./mvnw -B test

      - name: Package
        run: ./mvnw -B -DskipTests clean package
